# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Logos.Technology
title: Logos | Technology
email: info@logos.technology
contact_phone: "+(511)-564-5744"
location: "Lima - Perú"
slogan: "si ud. lo sueña, nosotros lo creamos"
office_address: "Calle Elvira García y García 2642 Piso 4"
office_location: "Urb. Los Cipreses"
description: >- # this means to ignore newlines until "baseurl:"
  Logos Technology es una de las primeras empresas peruanas
  especializada exclusivamente en trabajar en el campo de
  tecnologías emergentes. Como un spin-off de inversión nuestra empresa
  matriz Eq Soft, hemos heredado el incentivo de incursionar constantemente
  en innovación y desarrollo de nuevos productos, construimos el mercado
  mercado de la siguientes olas de tecnología aplicada a las necesidades
  empresariales.
baseurl: "" # the subpath of your site, e.g. /archivo
# url: "http://logos.technology" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://logostech.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_comments: true
twitter_username: ltechper
facebook_page: logostechperu
github_username:  edux87
analytics: google
pricing:
  base: 0
  principiante: 9
  medio: 18
  avanzado: 37
# Build settings
paginate: 12
paginate_path: "/archivo/page:num/"
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
# excerpt_separator: <!--more-->
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: true              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: true       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: true      # Default: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - .gitignore
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
