# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Logos | Technology
email: info@logos.technology
contact_phone: "+(511)-564-5744"
location: "Lima - Perú"
slogan: "si ud. lo sueña, nosotros lo hacemos realidad"
office_address: "Calle Elvira García y García 2642 Piso 4"
office_location: "Urb. Los Cipreses"
description: >- # this means to ignore newlines until "baseurl:"
  Logos Technology es una de las primeras empresas peruanas
  especializada exclusivamente en trabajar en el campo de
  tecnologías emergentes. Como un spin-off de inversión nuestra empresa
  matriz Eq Soft, hemos heredado el incentivo de incursionar constantemente
  en innovación y desarrollo de nuevos productos, construimos el mercado
  mercado de la siguientes olas de tecnología aplicada a las necesidades
  empresariales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://logos.technology" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ltechper
facebook_page: logostechperu
github_username:  edux87
analytics: googlex
pricing:
  base: 0
  principiante: 9
  medio: 18
  avanzado: 37
# Build settings
paginate: 12
paginate_path: "/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
# excerpt_separator: <!--more-->
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - .gitignore
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
